### ISSUE TITLE
Update Overall Pages/URL Structure

### ISSUE THREAD

**Issue by tylergaw** [ideas42ventures/ideas42ventures.com#22]
Now that we have near-complete content https://docs.google.com/document/d/1zn-6Nvp6K6g-QbNpGSWxTQLISVqvg8vxm50wlDjXfy8/edit?ts=5f2c096a&pli=1 we have new and changed pages, so new URLs.

### For this issue
- We want to have a working URL for every page of the site 
- Don't worry about content for the pages yet, placeholder is fine for now.
- We don't need to update the banner or footer navigation for this
- For this, we just need to be able to type in each URL directly to see that they're all in place, it's OK if there are not links to each page

A good way to see each page is via the Figma prototype: https://www.figma.com/proto/5ThSdBlZBcQnuyk15DWJNQ/Venture-Studio---Site?node-id=52%3A0&scaling=min-zoom

Outline. Some of these exist already, some are new, some are suggested URLs, but we there might be better ones

- Home `/`
- About `/about`
- FAQ `/faq`
- Ventures for Shared Prosperity `/ventures-for-shared-prosperity`
  - VSP / Focus area `/ventures-for-shared-prosperity/focus-area`
  - VSP / What we provide `/ventures-for-shared-prosperity/what-we-provide`
  - VSP / Apply `/ventures-for-shared-prosperity/apply`
- Apply `/apply` 301 redirect to `/ventures-for-shared-prosperity/apply`

Couple things to note:

- The `/ventures-for-shared-prosperity` and sub pages is something that we'll do for this cohort and for future cohorts. They're like mini sites within the main site
- I *think* we're going to want a `/cohorts` page at some point to list all cohorts, but I'm not sure we need that there yet. If we end up sticking with the drop down menu we will, but that's still TBD

#### Reference
- [11ty docs](https://www.11ty.dev/docs/) for info on how pages, urls work in eleventy
- [Netlify redirect docs](https://docs.netlify.com/routing/redirects/) Also, we have a Netlify conf file in the root.

**Comment by tylergaw** [comment]
@will0101 Let me know if I can clarify anything or if you have any questions

**Comment by will0101** [comment]
Hey, I need access to the Google doc. Also, just so I'm clear on the task would you like me to create the new banner that's based off the Figma design or just add the links based on the version that I have?

**Comment by tylergaw** [comment]
Made a change to the description to be more clear. For this, we don't need to update the banner or footer nav. It's OK if we don't have visible links yet. For this work we only need to be able to manually type in the URL to see that there is a page there for each. So we're looking for the template files and directories set up for that to work

**Comment by will0101** [comment]
Thanks for clearing this up. I'll get started now.

**Comment by tylergaw** [comment]
Completed in #24
