### ISSUE TITLE
Mark up Ventures for Shared Prosperity Content

### ISSUE THREAD

**Issue by tylergaw** [ideas42ventures/ideas42ventures.com#25]
### Task

Using semantic HTML, add the text content from the [Figma mockups](https://www.figma.com/file/5ThSdBlZBcQnuyk15DWJNQ/Venture-Studio-Site?node-id=538%3A1) to the four Ventures for Shared Prosperity (VSP) pages.

For this issue, we're **not** interested in:
- The global banner or global footer, only the content unique to VSP
- Styling or images. Only interested in having the text content in the pages described with appropriate HTML elements. This includes links both internal and external.

### End Result

For this to be considered completed, we need to be able to see the four pages on a Netlify preview site. We should be able to click the links between each page to navigate to them all and see the content that's currently in the Figma mock ups

The pages:
- [x] VSP landing
- [x] VSP Apply
- [x] VSP Focus Area
- [x] VSP What We Provide

**Comment by tylergaw** [comment]
@will0101 Got a next one for you. Once you're wrapped up with your current PR, let's talk about this one.

**Comment by will0101** [comment]
@tylergaw Hey, I "finished" this one. Just have a few Git issues, I branched off from one of my branches instead of `main` to make the changes 😩. But, I should have that cleaned up soon.

**Comment by tylergaw** [comment]
@will0101 Cool. When you're ready for me, hit the request review btn

**Comment by tylergaw** [comment]
@will0101 When you merge a PR for an issue, you can go ahead and close it. Also, if you write "fixes #25" in the PR description or comment, Github will auto close that issue when you merge.
