### ISSUE TITLE
Mark up About Us Page

### ISSUE THREAD

**Issue by tylergaw** [ideas42ventures/ideas42ventures.com#32]
Figma (working): https://www.figma.com/file/5ThSdBlZBcQnuyk15DWJNQ/Venture-Studio-Site?node-id=585%3A49Fig
Figma (prototype): https://www.figma.com/proto/5ThSdBlZBcQnuyk15DWJNQ/Venture-Studio---Site?node-id=585%3A49&scaling=min-zoom

For the About Us page, add the content and html mark up. The same as #25, for this issue we're only concerned with content and markup. Not concerned with any styles or design decorations.

For the team member photos, for now, use any image with a similar aspect ratio. Can be from https://placeholder.com/

**Comment by tylergaw** [comment]
@will0101 Got a new one for you here when you're ready.

**Comment by will0101** [comment]
@tylergaw Ready when you are 👍.
