### ISSUE TITLE
VSP Landing: Consider adding Marc's photo to the Q&A Session Banner

### ISSUE THREAD

**Issue by tylergaw** [ideas42ventures/ideas42ventures.com#77]
The graphic here:

![Screen Shot 2020-09-30 at 9 28 28 AM](https://user-images.githubusercontent.com/233859/94691463-51f72700-02ff-11eb-83ed-e34a53091c23.png)

These photos aren't really meant to be taken literal, also no one will know who these faces are outside of us, but still could consider adding Marc's photo as well.

**Comment by will0101** [comment]
Thoughts, maybe we can create **bios** for individual team members. Since the entrepreneurs that will be applying have no prior knowledge of us and our specialties. It might be cool to have introductions outside of our Linkedin profiles.

**Comment by tylergaw** [comment]
@will0101 yeah, was trying to avoid bio content just for right now mostly because writing/getting bios for team members tends to be tough, but something we should consider adding in the future.

Added Marc in #85
