### ISSUE TITLE
Send Newsletter Sign Ups to Buttondown

### ISSUE THREAD

**Issue by tylergaw** [ideas42ventures/ideas42ventures.com#89]
We started this work in #80. And we can continue using the code we have in-progress in #81.

### What we want

When a user signs up for the newsletter via the form in the site footer, we want their email (and the tag) to go directly to Buttondown via its [api](https://api.buttondown.email/v1/schema#operation/createSubscriber).

This means that we'll no longer need Netlify form handling for this form. This has been the end-goal, the idea behind the current work in #81 was to take a first step. But because of the [trouble we ran into](https://community.netlify.com/t/is-it-possible-to-modify-the-response-of-a-submission-created-function/24909) with trying to customize the response of a `submission-created` handler, we'll skip over that step.

### Things that change
- We no longer want a `submission-created` handler because we won't be submitting a Netlify form, instead our function (named something like `signup-form-handler.js`) will take care of processing the form
- We don't need Netlify-related attributes on the html form

### More things we're looking for

We need the form to work with and without JavaScript. This should be a progressively enhanced form. There's a great example showing this exact setup here https://github.com/netlify-labs/progressive-form-enhancement-via-functions

When the form is submitted without JavaScript, we want the user directed to our `/subscribed` page. Their info should be sent to Buttondown in the exact way it is when JS is enabled.

### Development

We have a Buttondown account, but for development, create another account [https://buttondown.email/register](https://buttondown.email/register) and use its API key so we don't have to worry about harming live data. Once we see things working as expected we'll switch out the API key.

**Comment by tylergaw** [comment]
@will0101 Also on this. I'd like it to be live by this evening. If you start moving on this and it doesn't look like that is possible by like 4:30pm today. Let me know and I'll help push it along.

**Comment by will0101** [comment]
@tylergaw I'll start on this now.

**Comment by tylergaw** [comment]
Excellent, let me know if you want to talk through any of it. I have a 12-12:30 call but other than that I'm available

**Comment by tylergaw** [comment]
Done in #90
