### ISSUE TITLE
Update Content to Close Out VSP Applications

### ISSUE THREAD

**Issue by tylergaw** [ideas42ventures/ideas42ventures.com#95]
We've reached the end of applications for VSP. We need to remove content from the site that directs people to apply.

- Update Apply nav item button (TBD what we'll do with it)
- Update copy in current Apply CTA (or remove it)
- Remove "apply..." language from VSP pages
- Remove "Accepting applications..." badge from VSP subnav
- Update VSP timeline to show where we are in the process
- Remove note about QA sessions from VSP apply page

**Comment by marclaitin** [comment]
1) For clarity (i think this was your plan) lets not change any URLs for now, as there are lots of links out there to some of these subpages, and for the /apply page lets mostly keep it the same, but in the call out box at the right, note that applications are now closed for this cohort, but that we anticipate beginning recruitment for our next cohort in mid 2021 and have the sign up form embedded for people to be notified when we go live (we also need to put in links to the youtube videos on this page as i hadn't realized it had links to the zoom Q&A sign up)

2) agreed on the rest as we mostly can just call out "applications now closed", while keeping the language the same as it is good content to keep.
